export const INITIALIZE_PLAYER = "INITIALIZE_PLAYER";
export const LOAD_NEW_PLAYBACK_INSTANCE = "LOAD_NEW_PLAYBACK_INSTANCE";
export const LOADING_INSTANCE = "LOADING_INSTANCE";
export const PAUSE_PLAYBACK_INSTANCE = "PAUSE_PLAYBACK_INSTANCE";
export const PLAY_PLAYBACK_INSTANCE = "PLAY_PLAYBACK_INSTANCE";
export const SET_PLAYBACK_POSITION = "SET_PLAYBACK_POSITIION";
export const UPDATE_PLAYBACK_STATUS = "UPDATE_PLAYBACK_STATUS";
